name: todomvc
description: A TodoMVC app created using the Jaspr Dart web framework.
version: 0.1.0

environment:
    sdk: ^3.10.7

dependencies:
    jaspr: ^0.22.1

dev_dependencies:
    build_runner:
    build_web_compilers: ^4.1.2
    jaspr_builder:
    jaspr_lints:
    jaspr_cli: ^0.22.1
    lints:

jaspr:
    mode: client
